name: ODM
channels:
  - anaconda
  - defaults
  - conda-forge
dependencies:
  - matplotlib
  - mahotas
  - python=3.9.7
  - pyod
  - pip
  - scikit-learn
  - scikit-image=0.19.2
  - keras
  - hyperopt
  - pydicom
  - gdcm
  - cudatoolkit
  - pytest
  - psutil
  - pip:
      - pylibjpeg[all]
      - tensorflow
